version: '3'

services:
  typesense-1:
    image: typesense/typesense:0.21.0
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_NODES: /app/cluster.typesense.txt
    ports:
      - "8107:8107"
      - "8108:8108"
    volumes:
      - ./:/app
    tmpfs:
      - /data
    restart: always

  typesense-2:
    image: typesense/typesense:0.21.0
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_NODES: /app/cluster.typesense.txt
    ports:
      - "8207:8107"
      - "8208:8108"
    volumes:
      - ./:/app
    tmpfs:
      - /data
    restart: always

  typesense-3:
    image: typesense/typesense:0.21.0
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_NODES: /app/cluster.typesense.txt
    ports:
      - "8307:8107"
      - "8308:8108"
    volumes:
      - ./:/app
    tmpfs:
      - /data
    restart: always
